"""Redesign ReconciliationRecord

Revision ID: 4764544f4a05
Revises: 
Create Date: 2026-05-22 09:28:00.645710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4764544f4a05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reconciliation_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_record_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('internal_old_tag', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('internal_new_tag', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('internal_year', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('internal_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('internal_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('internal_serial_no', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('internal_department', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('internal_district', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('internal_book_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('internal_asset_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_old_tag', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('customer_new_tag', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('customer_year', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('customer_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('customer_serial_no', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('customer_department', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('customer_district', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('customer_book_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('match_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('match_method', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.drop_column('customer_data')
        batch_op.drop_column('internal_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reconciliation_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_data', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('customer_data', mysql.JSON(), nullable=True))
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('match_method')
        batch_op.drop_column('match_type')
        batch_op.drop_column('customer_book_value')
        batch_op.drop_column('customer_district')
        batch_op.drop_column('customer_department')
        batch_op.drop_column('customer_serial_no')
        batch_op.drop_column('customer_description')
        batch_op.drop_column('customer_category')
        batch_op.drop_column('customer_year')
        batch_op.drop_column('customer_new_tag')
        batch_op.drop_column('customer_old_tag')
        batch_op.drop_column('internal_asset_number')
        batch_op.drop_column('internal_book_value')
        batch_op.drop_column('internal_district')
        batch_op.drop_column('internal_department')
        batch_op.drop_column('internal_serial_no')
        batch_op.drop_column('internal_description')
        batch_op.drop_column('internal_category')
        batch_op.drop_column('internal_year')
        batch_op.drop_column('internal_new_tag')
        batch_op.drop_column('internal_old_tag')
        batch_op.drop_column('full_record_json')

    # ### end Alembic commands ###
